; War3 Effect Designer Configurations
; You may eidt the sections to change setup manually.
; Copyright (C) 2017 - 2019 yxq1122. All rights reserved.

[General]
languagefile=lang\eng.lang
EnableTimeRange=false
MaxHistory=4
ProjectDir=projects
Font=Use default font
BKColor=f0f0f0
BKImage=skins\e0b35.jpeg
SchemeRegionColor=008000
TextBufferSize=1024
FileEncode=ANSI

[StuffList]
BKColor=f0f0f0
TextColor=000080
TextBKColor=c0ff00

[UnitFilter]
BKColor=ffffff
TypeColor=008080
TypeBKColor=ffffff
LogicColor=ff0000
LogicBKColor=ffffff

[Previewer]
MaxPlaySpeed=100
MinPlaySpeed=5
ElementSize=3
BKColor=000000
ElementColor=00ffff

[Compiler]
NewHashtable=true
EnableAnnotation=true
Language=vJass

[CodeEditor]
BKColor =000039
DefaultTextColor =ffff00
Editable=false
Font=Times New Roman(-13)
EnableIndent=true
IndentStrategy=Double Space
IndentCount=1
SyntaxHighLighting=true
KeyWords=008080
Types=00ff4a
Strings=ff00ff
Annotations=808080
Functions=ff0000


[CustomInitEqs]
0=myeq1 | z0(0) = 0;b = GetRandomReal(1, 3);[loop] a = 0 | 1 | b;r(0) = GetRandomReal(300, 500);sita(0) = GetRandomReal(0, 360);ang(0) = GetRandomReal(0, 90);x = x0 + r * CosBJ(ang) * CosBJ(sita);y = y0 + r * CosBJ(ang) * SinBJ(sita);z = z0 + r * SinBJ(ang);
1=InitEqs | [loop] sita = 0 | 10 | 78;r = 0.5 * sita;x = x0 + r * CosBJ(sita);y = y0 + r * SinBJ(sita);

[CustomMoveEqs]
0=parabo2 | ang=60;a=42;v0=150;x=x0+ r*CosBJ(sita);y=y0+ r*SinBJ(sita);z=r * TanBJ(ang) - 0.5 * a * r * r/Pow(v0*CosBJ(ang), 2);r = r + 50;
1=parabo1 | x = x0 + r * CosBJ(sita);y = y0 + r * SinBJ(sita);z = 400 / Pow(500, 2) * Pow((r-500), 2);r = r + 80;
2=myeq1 | x = x0 + r * CosBJ(ang) * CosBJ(sita);y = y0 + r * CosBJ(ang) * SinBJ(sita);z = z0 + r * SinBJ(ang);r = r - 30;
3=parabo3 | x = x0 + r * CosBJ(sita);y = y0 + r * SinBJ(sita);z = 400 - 400 / Pow(500, 2) * Pow(r, 2);r = r + 80;

[CustomActions]

[CustomAttrs]
[Histories]
2=C:\Users\vsus\Documents\Visual Studio 2015\Projects\war3\Release\projects\eff2.epf
3=C:\Users\vsus\Documents\Visual Studio 2015\Projects\war3\Release\projects\eff3.epf
4=C:\Users\vsus\Documents\Visual Studio 2015\Projects\war3\Release\projects\eff1.epf
5=C:\Users\vsus\Documents\Visual Studio 2015\Projects\war3\Release\projects\eff12.epf
