(function(){
  'use strict';
  const C=window.WC3_EFFECTS_CORE;if(!C)return;
  const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
  const state={
    epf:C.createDefaultEpf(),epfPath:'',selectedLayer:'Layer00',selectedStuff:'',scriptLang:'lua',
    bundlePath:'',bundleName:'',bundleFiles:C.blankBundle(),bundle:C.parseBundle(C.blankBundle()),
    selectedSampler:'',selectedRenderer:'',codeFile:'effect.cfx',bridge:null,dirtyBundle:false,testMode:false,
    motionLayoutToken:0,motionLayoutSig:'',motionResizeObserver:null,motionDprOverride:null
  };
  const bridge=()=>state.bridge||window.WC3_EFFECTS||{};
  const log=(level,msg,detail)=>window.WC3_LOG?.[level]?.('Effects Lab',msg,detail);
  const appError=(msg,detail)=>log(state.testMode?'debug':'error',msg,detail);
  const status=msg=>window.BLP_PAINT_APP?.setStatus?.(msg);
  const safeHtml=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const debounce=(fn,ms=120)=>{let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),ms)}};
  function selectedLayer(){return state.epf.layers.find(x=>x.section===state.selectedLayer)||state.epf.layers[0]||null}
  function selectedLayerStuffs(){const layer=selectedLayer();return layer?C.epfStuffsForLayer(state.epf,layer.section):[]}
  function selectedStuff(){const stuffs=selectedLayerStuffs();return stuffs.find(x=>x.section===state.selectedStuff)||stuffs[0]||null}
  function setView(view){const allowed=new Set(['designer','cfx','graph','samplers','renderers','code']);view=allowed.has(view)?view:'designer';$$('.effects-tab').forEach(b=>b.classList.toggle('active',b.dataset.effectsView===view));$$('.effects-view').forEach(p=>p.classList.toggle('active',p.dataset.effectsPanel===view));if(view==='graph')renderGraph();if(view==='samplers')renderSamplers();if(view==='renderers')renderRenderers();if(view==='code')renderCodeTabs();if(view==='designer')scheduleEffectsLayoutRefresh('designer-view',3);return view}
  function syncEpf(){state.epf=C.parseEpf(C.serializeIni(state.epf.doc));}
  function setVal(section,key,value){C.setIniValue(state.epf.doc,section,key,String(value??''));syncEpf()}
  function currentProjectName(){return state.epf.general.Name||'Effect'}
  function refreshProject(){renderProjectTree();renderProjectInspector();renderMotion();renderScript()}
  function renderProjectTree(){
    const host=$('#effectsLayerTree');if(!host)return;host.innerHTML='';
    state.epf.layers.forEach((l,i)=>{const v=l.values,btn=document.createElement('button');btn.type='button';btn.className='effects-tree-row'+(l.section===state.selectedLayer?' active':'');btn.innerHTML=`<span class="fx-tree-main"><strong>${safeHtml(v.LayerName||`Layer ${i+1}`)}</strong><span>${safeHtml(l.section)} · ${(Number(v.LayerDur||v.DurTime||0)||0).toFixed(2)}s · ${safeHtml(v.Intv||state.epf.general.Period||'0.03')} tick</span></span><small>${v.LayerType==='1'?'RELATED':'INDEPENDENT'}</small>`;btn.addEventListener('click',()=>{state.selectedLayer=l.section;const stuffs=selectedLayerStuffs();state.selectedStuff=stuffs.some(x=>x.section===state.selectedStuff)?state.selectedStuff:(stuffs[0]?.section||'');renderProjectTree();renderProjectInspector();renderMotion()});host.appendChild(btn)});
    const sh=$('#effectsStuffList');if(!sh)return;sh.innerHTML='';const stuffs=selectedLayerStuffs();if(!stuffs.some(x=>x.section===state.selectedStuff))state.selectedStuff=stuffs[0]?.section||'';stuffs.forEach((st,i)=>{const v=st.values,btn=document.createElement('button');btn.type='button';btn.className='effects-list-row'+(st.section===state.selectedStuff?' active':'');btn.innerHTML=`<span>${safeHtml(C.epfStuffField(v,'type')||C.epfStuffField(v,'path')||v.DestId||`Object ${i+1}`)}</span><small>${safeHtml(st.section)}</small>`;btn.addEventListener('click',()=>{state.selectedStuff=st.section;renderProjectTree();renderProjectInspector()});sh.appendChild(btn)});
  }
  function setInput(id,value){const el=$('#'+id);if(el&&document.activeElement!==el)el.value=value??''}
  function renderProjectInspector(){
    const g=state.epf.general||{};setInput('effectsProjectName',g.Name||'');setInput('effectsPeriod',g.Period||'0.03');setInput('effectsProbability',g.Probability||'100');setInput('effectsTriggerType',g.TriggerType||'0');setInput('effectsTargetType',g.ObjectType||'0');setInput('effectsAbilityId',g.AbilityId||'');setInput('effectsHashtable',g.Hashtable||'ht');
    const l=selectedLayer()?.values||{};setInput('effectsLayerName',l.LayerName||'');setInput('effectsLayerType',l.LayerType||'0');setInput('effectsRefPoint',l.RefPoint||'0');setInput('effectsLayerStart',l.StartTime||'0');setInput('effectsLayerDuration',l.LayerDur||l.DurTime||'2');setInput('effectsLayerInterval',l.Intv||g.Period||'.03');setInput('effectsCorrLayer',l.CorrLayer||'');
    const st=selectedStuff(),v=st?.values||{};$('#effectsStuffSection').textContent=st?.section||'—';setInput('effectsStuffType',C.epfStuffField(v,'type'));setInput('effectsStuffScale',C.epfStuffField(v,'scale'));setInput('effectsStuffPath',C.epfStuffField(v,'path'));setInput('effectsStuffLife',C.epfStuffField(v,'life'));setInput('effectsStuffAnim',C.epfStuffField(v,'animation')||'stand');
    $('#effectsProjectPath').textContent=state.epfPath||'New EPF project';
  }
  function inferStuffType(v){return C.inferEpfStuffType(v)}
  function motionCanvasLayout(reason='render'){
    const cv=$('#effectsMotionCanvas');if(!cv)return null;
    const rect=cv.getBoundingClientRect(),visible=document.body.dataset.module==='effects'&&cv.offsetParent!==null&&rect.width>=32&&rect.height>=32;
    if(!visible)return null;
    const rawDpr=Number.isFinite(Number(state.motionDprOverride))?Number(state.motionDprOverride):Number(window.devicePixelRatio),dpr=Math.min(2,Math.max(1,rawDpr||1)),w=Math.max(1,Math.round(rect.width*dpr)),h=Math.max(1,Math.round(rect.height*dpr)),resized=cv.width!==w||cv.height!==h;
    if(resized){cv.width=w;cv.height=h;}
    const sig=`${Math.round(rect.width)}x${Math.round(rect.height)}@${dpr}:${w}x${h}`;
    if(sig!==state.motionLayoutSig){
      state.motionLayoutSig=sig;
      log('debug','Motion preview layout synchronized',{reason,css:{width:+rect.width.toFixed(2),height:+rect.height.toFixed(2)},backing:{width:w,height:h},dpr,resized});
    }
    return{cv,rect,dpr,w,h,resized};
  }
  function drawMotion(reason='render'){
    const layout=motionCanvasLayout(reason);if(!layout)return false;
    const {cv,dpr,w,h}=layout,ctx=cv.getContext('2d');ctx.clearRect(0,0,w,h);ctx.save();ctx.scale(dpr,dpr);const W=w/dpr,H=h/dpr,cx=W/2,cy=H*.57,scale=Math.min(W,H)*.18;
    ctx.strokeStyle='rgba(110,133,149,.18)';ctx.lineWidth=1;for(let i=-4;i<=4;i++){ctx.beginPath();ctx.moveTo(0,cy+i*scale*.5);ctx.lineTo(W,cy+i*scale*.5);ctx.stroke();ctx.beginPath();ctx.moveTo(cx+i*scale*.5,0);ctx.lineTo(cx+i*scale*.5,H);ctx.stroke();}
    ctx.strokeStyle='rgba(205,165,78,.45)';ctx.beginPath();ctx.moveTo(0,cy);ctx.lineTo(W,cy);ctx.moveTo(cx,0);ctx.lineTo(cx,H);ctx.stroke();
    const finite=(id,fallback)=>{const n=Number($('#'+id)?.value);return Number.isFinite(n)?n:fallback},opts={count:100,radius:finite('effectsMotionRadius',1),height:finite('effectsMotionHeight',1.5),turns:finite('effectsMotionTurns',2.5),length:3};
    const init=C.initialShapePoints($('#effectsInitPreset')?.value||'None',{...opts,count:48});ctx.save();ctx.setLineDash([2,5]);init.forEach(p=>{const sx=cx+(p.x-p.y*.38)*scale,sy=cy-(p.z+p.y*.22)*scale;ctx.beginPath();ctx.arc(sx,sy,2.2,0,Math.PI*2);ctx.fillStyle='rgba(132,190,217,.55)';ctx.fill()});ctx.restore();
    const pts=C.motionPoints($('#effectsMotionPreset')?.value||'Line',opts);const moving=($('#effectsMotionPreset')?.value||'Line')!=='None';if(moving){ctx.beginPath();pts.forEach((p,i)=>{const sx=cx+(p.x-p.y*.38)*scale,sy=cy-(p.z+p.y*.22)*scale;i?ctx.lineTo(sx,sy):ctx.moveTo(sx,sy)});ctx.strokeStyle='#f0c65d';ctx.lineWidth=2;ctx.stroke();}
    pts.filter((_,i)=>moving&&i%10===0).forEach((p,i)=>{const sx=cx+(p.x-p.y*.38)*scale,sy=cy-(p.z+p.y*.22)*scale;ctx.beginPath();ctx.arc(sx,sy,i===0?4:2.3,0,Math.PI*2);ctx.fillStyle=i===0?'#fff2aa':'#d2a94d';ctx.fill()});ctx.restore();return true;
  }
  function renderMotion(reason='render'){const preset=$('#effectsMotionPreset')?.value||'Line',init=$('#effectsInitPreset')?.value||'None';$('#effectsMotionBadge').textContent=`${preset.toUpperCase()} · INIT ${init.toUpperCase()}`;return drawMotion(reason)}
  function scheduleEffectsLayoutRefresh(reason='workspace',attempts=4){
    const token=++state.motionLayoutToken,max=Math.max(1,Number(attempts)||1);
    const step=left=>requestAnimationFrame(()=>{if(token!==state.motionLayoutToken||document.body.dataset.module!=='effects')return;let ok=true;if(currentView()==='designer')ok=renderMotion(reason);else if(currentView()==='graph')renderGraph();if(!ok&&left>1)step(left-1);});
    step(max);return token;
  }
  function installMotionResizeObserver(){
    const stage=$('.effects-preview-stage');if(!stage||typeof ResizeObserver!=='function')return;
    try{state.motionResizeObserver?.disconnect?.();}catch(_){}
    state.motionResizeObserver=new ResizeObserver(entries=>{if(document.body.dataset.module!=='effects'||currentView()!=='designer')return;const r=entries?.[0]?.contentRect;if(!r||r.width<32||r.height<32)return;scheduleEffectsLayoutRefresh('resize-observer',2);});
    state.motionResizeObserver.observe(stage);
  }
  function renderScript(){const out=C.generateEffectScript(state.epf,state.scriptLang);const ta=$('#effectsGeneratedScript');if(ta&&document.activeElement!==ta)ta.value=out;$('#effectsScriptMeta').textContent=`${state.scriptLang==='jass'?'JASS':'Lua'} · ${state.epf.layers.length} layer${state.epf.layers.length===1?'':'s'}`;$$('[data-effects-script-lang]').forEach(b=>b.classList.toggle('active',b.dataset.effectsScriptLang===state.scriptLang))}

  function markBundleDirty(){state.dirtyBundle=true;renderBundleSummary()}
  function parseBundle(){state.bundle=C.parseBundle(state.bundleFiles);return state.bundle}
  function loadBundle(payload){state.bundlePath=payload?.path||'';state.bundleName=payload?.name||state.bundlePath.split(/[\\/]/).pop()||'effect.cfxb';state.bundleFiles={...C.blankBundle(),...(payload?.files||{})};state.dirtyBundle=false;parseBundle();renderBundleAll();status(`Effects Lab: ${state.bundleName}`)}
  function renderBundleAll(){renderBundleSummary();renderGraph();renderSamplers();renderRenderers();renderCodeTabs()}
  function renderBundleSummary(){const b=state.bundle||parseBundle();$('#effectsBundlePath').textContent=state.bundlePath||`${state.bundleName||'Unsaved bundle'} · in memory`;$('#effectsBundleState').textContent=state.dirtyBundle?'MODIFIED':state.bundlePath?'LOADED':'MEMORY';$('#effectsMetricLayers').textContent=b.layers.length;$('#effectsMetricRenderers').textContent=b.renderers.length;$('#effectsMetricSamplers').textContent=b.samplers.length;$('#effectsMetricAttrs').textContent=b.attributes.length;$('#effectsFlowSummary').innerHTML=`<strong>${b.graph.spawns.length} spawn root${b.graph.spawns.length===1?'':'s'}</strong> · ${b.graph.emits.length} event edge${b.graph.emits.length===1?'':'s'}<br>${b.graph.emits.map(e=>`${safeHtml(e.from)} — ${safeHtml(e.event)} → ${safeHtml(e.to)}`).join('<br>')||'No emit edges detected.'}`;const host=$('#effectsBundleFiles');host.innerHTML='';C.bundleFileList(state.bundleFiles).forEach(name=>{const v=state.bundleFiles[name]||'',el=document.createElement('button');el.className='effects-file-chip';el.innerHTML=`<strong>${name}</strong><small>${v.length.toLocaleString()} chars</small>`;el.onclick=()=>{state.codeFile=name;setView('code');renderCodeTabs()};host.appendChild(el)});}
  function renderGraph(){const host=$('#effectsGraphStage');if(!host)return;const b=state.bundle||parseBundle();$('#effectsGraphLayerCount').textContent=String(b.layers.length);const list=$('#effectsCfxLayerList');list.innerHTML='';b.layers.forEach(l=>{const row=document.createElement('button');row.className='effects-list-row';row.innerHTML=`<span>${safeHtml(l.name)}</span><small>${l.renderers.length?`${l.renderers.length} renderer`:''}</small>`;row.onclick=()=>{state.codeFile='code.cfx';setView('code');renderCodeTabs();const ta=$('#effectsCfxCode');const pos=ta.value.indexOf(`layer ${l.name}`);if(pos>=0){ta.focus();ta.setSelectionRange(pos,pos)}};list.appendChild(row)});
    host.innerHTML='';const names=[...new Set([...b.graph.spawns,...b.graph.emits.flatMap(e=>[e.from,e.to]).filter(Boolean),...b.layers.map(l=>l.name)].filter(Boolean))];if(!names.length){host.innerHTML='<div class="casc-gallery-empty">No graph nodes detected. Open or decompile a CFX bundle.</div>';return}const width=Math.max(720,host.clientWidth||720),cols=Math.max(2,Math.ceil(Math.sqrt(names.length)));const positions=new Map();names.forEach((n,i)=>{const col=i%cols,row=Math.floor(i/cols),x=40+col*((width-180)/cols),y=40+row*110;positions.set(n,{x,y});});b.graph.emits.forEach(e=>{const a=positions.get(e.from),z=positions.get(e.to);if(!a||!z)return;const x1=a.x+125,y1=a.y+25,x2=z.x,y2=z.y+25,dx=x2-x1,dy=y2-y1,len=Math.hypot(dx,dy),ang=Math.atan2(dy,dx)*180/Math.PI;const edge=document.createElement('div');edge.className='effects-graph-edge';edge.style.cssText=`left:${x1}px;top:${y1}px;width:${len}px;transform:rotate(${ang}deg)`;edge.innerHTML=`<span>${safeHtml(e.event)}</span>`;host.appendChild(edge)});names.forEach(n=>{const p=positions.get(n),node=document.createElement('div');node.className='effects-graph-node'+(b.graph.spawns.includes(n)?' root':'');node.style.cssText=`left:${p.x}px;top:${p.y}px`;const layer=b.layers.find(l=>l.name===n);node.innerHTML=`<strong>${safeHtml(n)}</strong><small>${b.graph.spawns.includes(n)?'SPAWN ROOT':layer?`${layer.renderers.length} renderer(s)`:'EVENT NODE'}</small>`;host.appendChild(node)});
  }
  function renderSamplers(){const b=state.bundle||parseBundle(),list=$('#effectsSamplerList');if(!list)return;$('#effectsSamplerCount').textContent=String(b.samplers.length);list.innerHTML='';if(!state.selectedSampler&&b.samplers[0])state.selectedSampler=b.samplers[0].name;for(const s of b.samplers){const row=document.createElement('button');row.className='effects-list-row'+(state.selectedSampler===s.name?' active':'');row.innerHTML=`<span>${safeHtml(s.name)}</span><small>${safeHtml(s.subtype||s.kind)}</small>`;row.onclick=()=>{state.selectedSampler=s.name;renderSamplers()};list.appendChild(row)}const sel=b.samplers.find(x=>x.name===state.selectedSampler)||b.samplers[0];$('#effectsSamplerSource').value=sel?.text||'// No sampler selected.';drawCurveFromText(sel?.text||'')}
  function drawCurveFromText(src){const cv=$('#effectsCurveCanvas');if(!cv)return;const rect=cv.getBoundingClientRect(),w=Math.max(300,Math.round(rect.width)),h=150;cv.width=w;cv.height=h;const ctx=cv.getContext('2d');ctx.clearRect(0,0,w,h);ctx.strokeStyle='#263540';ctx.beginPath();ctx.moveTo(20,h-20);ctx.lineTo(w-10,h-20);ctx.moveTo(20,10);ctx.lineTo(20,h-20);ctx.stroke();const keys=[...String(src).matchAll(/^\s*([0-9.]+)\s*=\s*\(?\s*([-+0-9.eE]+)/gm)].map(m=>({t:Number(m[1]),v:Number(m[2])})).filter(p=>Number.isFinite(p.t)&&Number.isFinite(p.v));if(keys.length<2){ctx.fillStyle='#627481';ctx.font='11px sans-serif';ctx.fillText('No numeric curve keyframes detected in selected sampler.',32,42);return}const min=Math.min(...keys.map(x=>x.v)),max=Math.max(...keys.map(x=>x.v));ctx.beginPath();keys.forEach((p,i)=>{const x=20+p.t*(w-35),y=h-20-((p.v-min)/(max-min||1))*(h-40);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle='#e0b756';ctx.lineWidth=2;ctx.stroke();for(const p of keys){const x=20+p.t*(w-35),y=h-20-((p.v-min)/(max-min||1))*(h-40);ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fillStyle='#f3d980';ctx.fill()}}
  function renderRenderers(){const b=state.bundle||parseBundle(),list=$('#effectsRendererList');if(!list)return;$('#effectsRendererCount').textContent=String(b.renderers.length);list.innerHTML='';if(!state.selectedRenderer&&b.renderers[0])state.selectedRenderer=b.renderers[0].name;for(const r of b.renderers){const sm=C.rendererSummary(r),row=document.createElement('button');row.className='effects-list-row effects-renderer-card'+(state.selectedRenderer===r.name?' active':'');row.innerHTML=`<span>${safeHtml(r.name)} · ${safeHtml(sm.type)}</span><small>${safeHtml(sm.blend||'default')}</small><em>${safeHtml(sm.texture||'No diffuse texture')}</em>`;row.onclick=()=>{state.selectedRenderer=r.name;renderRenderers()};list.appendChild(row)}const sel=b.renderers.find(x=>x.name===state.selectedRenderer)||b.renderers[0],sm=sel?C.rendererSummary(sel):null;$('#effectsRendererSource').value=sel?.text||'// No renderer selected.';$('#effectsRendererSummary').innerHTML=sm?`<strong>${safeHtml(sm.type)}</strong> · blend <b>${safeHtml(sm.blend||'default')}</b> · texture <b>${safeHtml(sm.texture||'none')}</b>${sm.atlas?` · atlas <b>${safeHtml(sm.atlas)}</b>`:''}`:'Select a renderer.'}
  function renderCodeTabs(){const host=$('#effectsCodeTabs');if(!host)return;host.innerHTML='';for(const name of C.bundleFileList(state.bundleFiles)){const b=document.createElement('button');b.className='effects-code-tab'+(state.codeFile===name?' active':'');b.textContent=name;b.onclick=()=>{applyCodeToState();state.codeFile=name;renderCodeTabs()};host.appendChild(b)}const ta=$('#effectsCfxCode');if(ta)ta.value=state.bundleFiles[state.codeFile]||'';$('#effectsCodeMeta').textContent=`${state.bundleName||'Unsaved bundle'} · ${state.codeFile} · ${(state.bundleFiles[state.codeFile]||'').length.toLocaleString()} chars${state.dirtyBundle?' · modified':''}`}
  function applyCodeToState(){const ta=$('#effectsCfxCode');if(!ta)return;state.bundleFiles[state.codeFile]=ta.value;markBundleDirty();parseBundle()}
  function applySelectedBlock(kind){const b=state.bundle||parseBundle();if(kind==='sampler'){const old=b.samplers.find(x=>x.name===state.selectedSampler);if(!old)return;state.bundleFiles['samplers.cfx']=C.replaceBlock(state.bundleFiles['samplers.cfx'],old,$('#effectsSamplerSource').value);markBundleDirty();parseBundle();renderSamplers()}else{const old=b.renderers.find(x=>x.name===state.selectedRenderer);if(!old)return;state.bundleFiles['renderers.cfx']=C.replaceBlock(state.bundleFiles['renderers.cfx'],old,$('#effectsRendererSource').value);markBundleDirty();parseBundle();renderRenderers()}renderBundleSummary()}
  async function copyText(v){try{await navigator.clipboard.writeText(v);status('Copied to clipboard.')}catch(_){const ta=document.createElement('textarea');ta.value=v;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();status('Copied to clipboard.')}}
  async function withBusy(btn,fn){if(!btn)return fn();const old=btn.innerHTML;btn.disabled=true;btn.textContent='Working…';try{return await fn()}finally{btn.disabled=false;btn.innerHTML=old}}
  function consoleText(msg,detail=''){const el=$('#effectsToolConsole');if(el)el.textContent=`${msg}${detail?`\n\n${detail}`:''}`}
  async function refreshToolStatus(){try{const st=await bridge().status?.(),el=$('#effectsToolStatus');if(!el)return;if(st?.ready){el.textContent='Effects backend · READY';el.className='effects-tool-status ok';consoleText('Effects backend ready.')}else{el.textContent='Effects backend · MISSING';el.className='effects-tool-status bad';consoleText('Effects backend is missing. Re-apply the Effects Lab patch.')}}catch(e){const el=$('#effectsToolStatus');if(el){el.textContent='Effects backend · ERROR';el.className='effects-tool-status bad';}consoleText('Effects backend status failed.',e.message)}}

  function bindProjectFields(){
    const gmap={effectsProjectName:'Name',effectsPeriod:'Period',effectsProbability:'Probability',effectsTriggerType:'TriggerType',effectsTargetType:'ObjectType',effectsAbilityId:'AbilityId',effectsHashtable:'Hashtable'};for(const [id,key] of Object.entries(gmap))$('#'+id)?.addEventListener('change',e=>{setVal('General',key,e.target.value);renderScript();renderProjectTree()});
    const lmap={effectsLayerName:'LayerName',effectsLayerType:'LayerType',effectsRefPoint:'RefPoint',effectsLayerStart:'StartTime',effectsLayerDuration:'LayerDur',effectsLayerInterval:'Intv',effectsCorrLayer:'CorrLayer'};for(const [id,key] of Object.entries(lmap))$('#'+id)?.addEventListener('change',e=>{if(!state.selectedLayer)return;setVal(state.selectedLayer,key,e.target.value);renderProjectTree();renderScript();renderMotion()});
    const smap={effectsStuffType:'type',effectsStuffScale:'scale',effectsStuffPath:'path',effectsStuffLife:'life',effectsStuffAnim:'animation'};for(const [id,key] of Object.entries(smap))$('#'+id)?.addEventListener('change',e=>{if(!state.selectedStuff)return;C.setEpfStuffField(state.epf.doc,state.selectedStuff,key,e.target.value);syncEpf();renderProjectTree();renderProjectInspector()});
  }
  function bind(){
    $('#effectsTabs')?.addEventListener('click',e=>{const b=e.target.closest('[data-effects-view]');if(b)setView(b.dataset.effectsView)});
    $('#effectsNewProjectBtn')?.addEventListener('click',()=>{state.epf=C.createDefaultEpf();state.epfPath='';state.selectedLayer='Layer00';state.selectedStuff='Stuff000';refreshProject();status('New Effects Lab project')});
    $('#effectsLaunchDesignerBtn')?.addEventListener('click',()=>withBusy($('#effectsLaunchDesignerBtn'),async()=>{try{const r=await bridge().launchDesigner?.({path:state.epfPath});if(r?.ok)status('External compatibility tool launched.');}catch(e){status(`Compatibility tool launch failed: ${e.message||e}`);appError('Compatibility tool launch failed',e);}}));
    $('#effectsAddLayerBtn')?.addEventListener('click',()=>{const before=new Set(state.epf.layers.map(x=>x.section));state.epf=C.addEpfLayer(state.epf,state.selectedLayer);state.selectedLayer=state.epf.layers.find(x=>!before.has(x.section))?.section||state.selectedLayer;state.selectedStuff=C.epfStuffsForLayer(state.epf,state.selectedLayer)[0]?.section||'';refreshProject()});
    $('#effectsDeleteLayerBtn')?.addEventListener('click',()=>{if(state.epf.layers.length<=1)return status('Keep at least one layer.');const oldIndex=Math.max(0,state.epf.layers.findIndex(x=>x.section===state.selectedLayer));state.epf=C.removeEpfLayer(state.epf,state.selectedLayer);state.selectedLayer=state.epf.layers[Math.min(oldIndex,state.epf.layers.length-1)]?.section||state.epf.layers[0]?.section||'';state.selectedStuff=C.epfStuffsForLayer(state.epf,state.selectedLayer)[0]?.section||'';refreshProject()});
    $('#effectsAddStuffBtn')?.addEventListener('click',()=>{if(!state.selectedLayer)return;const before=new Set(state.epf.stuffs.map(x=>x.section));state.epf=C.addEpfStuff(state.epf,state.selectedLayer,'Effect');state.selectedStuff=C.epfStuffsForLayer(state.epf,state.selectedLayer).find(x=>!before.has(x.section))?.section||state.selectedStuff;refreshProject()});
    for(const id of ['effectsMotionPreset','effectsInitPreset','effectsMotionRadius','effectsMotionHeight','effectsMotionTurns'])$('#'+id)?.addEventListener('input',renderMotion);
    $$('[data-effects-script-lang]').forEach(b=>b.addEventListener('click',()=>{state.scriptLang=b.dataset.effectsScriptLang;renderScript()}));
    $('#effectsCopyScriptBtn')?.addEventListener('click',()=>copyText($('#effectsGeneratedScript').value));
    $('#effectsSaveScriptBtn')?.addEventListener('click',()=>withBusy($('#effectsSaveScriptBtn'),async()=>{try{const r=await bridge().saveCode?.({language:state.scriptLang,text:$('#effectsGeneratedScript').value,name:`${currentProjectName()}.${state.scriptLang==='jass'?'j':'lua'}`});if(!r?.canceled)status(`Saved ${r.name}`)}catch(e){status(`Script save failed: ${e.message||e}`);appError('Generated script save failed',e)}}));
    $('#effectsOpenEpfBtn')?.addEventListener('click',()=>withBusy($('#effectsOpenEpfBtn'),async()=>{const r=await bridge().chooseEpf?.();if(r?.canceled||!r?.text)return;state.epf=C.parseEpf(r.text);state.epfPath=r.path||'';state.selectedLayer=state.epf.layers[0]?.section||'';state.selectedStuff=C.epfStuffsForLayer(state.epf,state.selectedLayer)[0]?.section||'';refreshProject();status(`Opened ${r.name||'EPF project'}`)}));
    $('#effectsSaveEpfBtn')?.addEventListener('click',()=>withBusy($('#effectsSaveEpfBtn'),async()=>{const r=await bridge().saveEpf?.({path:state.epfPath,text:C.serializeIni(state.epf.doc),name:`${currentProjectName()}.epf`});if(!r?.canceled){state.epfPath=r.path||state.epfPath;renderProjectInspector();status(`Saved ${r.name}`)}}));
    $('#effectsNewBundleBtn')?.addEventListener('click',()=>{loadBundle({name:'new_effect.cfxb',files:C.blankBundle()});setView('cfx')});
    $('#effectsOpenBundleBtn')?.addEventListener('click',()=>withBusy($('#effectsOpenBundleBtn'),async()=>{const r=await bridge().chooseBundle?.();if(!r?.canceled)loadBundle(r)}));
    $('#effectsDecompileBtn')?.addEventListener('click',()=>withBusy($('#effectsDecompileBtn'),async()=>{const input=await bridge().choosePkb?.();if(input?.canceled)return;consoleText(`Decompiling ${input.name}…`);try{const r=await bridge().decompile?.({inputPath:input.path});if(!r?.canceled){loadBundle(r);consoleText(`Decompiled ${input.name}`,r.run?.stdout||'Bundle ready.')}}catch(e){consoleText('Decompile failed.',e.message);appError('Effects backend decompile failed',e)}}));
    const saveBundle=()=>withBusy($('#effectsSaveBundleBtn'),async()=>{applyCodeToState();const r=await bridge().saveBundle?.({bundlePath:state.bundlePath,files:state.bundleFiles,name:state.bundleName||'effect'});if(!r?.canceled){state.bundlePath=r.path;state.bundleName=r.path.split(/[\\/]/).pop();state.dirtyBundle=false;renderBundleSummary();status(`Saved ${state.bundleName}`)}return r});
    $('#effectsSaveBundleBtn')?.addEventListener('click',saveBundle);
    const build=btn=>withBusy(btn,async()=>{applyCodeToState();if(!state.bundlePath){const s=await saveBundle();if(!s||s.canceled)return}consoleText(`Building ${state.bundleName}…`);try{const r=await bridge().build?.({bundlePath:state.bundlePath});if(!r?.canceled){consoleText(`Built ${r.name}`,`${(r.bytes||0).toLocaleString()} bytes\n${r.run?.stdout||''}`);status(`Built ${r.name}`)}}catch(e){consoleText('Build failed.',e.message);appError('Effects backend build failed',e)}});
    $('#effectsBuildBtn')?.addEventListener('click',()=>build($('#effectsBuildBtn')));$('#effectsBuildTopBtn')?.addEventListener('click',()=>{setView('cfx');build($('#effectsBuildTopBtn'))});
    $('#effectsApplySamplerBtn')?.addEventListener('click',()=>applySelectedBlock('sampler'));$('#effectsApplyRendererBtn')?.addEventListener('click',()=>applySelectedBlock('renderer'));
    $('#effectsApplyCodeBtn')?.addEventListener('click',()=>{applyCodeToState();renderBundleAll();status(`Applied ${state.codeFile} to bundle`)});$('#effectsFormatCodeBtn')?.addEventListener('click',()=>{const ta=$('#effectsCfxCode');ta.value=ta.value.replace(/\r\n?/g,'\n').replace(/[ \t]+$/gm,'');applyCodeToState();renderCodeTabs()});
    bindProjectFields();window.addEventListener('resize',debounce(()=>{if(document.body.dataset.module==='effects')scheduleEffectsLayoutRefresh('window-resize',3)},120));
  }
  function currentView(){return $('.effects-tab.active')?.dataset.effectsView||'designer'}
  function snapshotState(){return{epfText:C.serializeIni(state.epf.doc),epfPath:state.epfPath,selectedLayer:state.selectedLayer,selectedStuff:state.selectedStuff,scriptLang:state.scriptLang,bundlePath:state.bundlePath,bundleName:state.bundleName,bundleFiles:{...state.bundleFiles},selectedSampler:state.selectedSampler,selectedRenderer:state.selectedRenderer,codeFile:state.codeFile,dirtyBundle:state.dirtyBundle,view:currentView()}}
  function restoreState(s){if(!s)return;state.epf=C.parseEpf(String(s.epfText||''));state.epfPath=String(s.epfPath||'');state.selectedLayer=s.selectedLayer||state.epf.layers[0]?.section||'';state.selectedStuff=s.selectedStuff||C.epfStuffsForLayer(state.epf,state.selectedLayer)[0]?.section||'';state.scriptLang=s.scriptLang==='jass'?'jass':'lua';state.bundlePath=String(s.bundlePath||'');state.bundleName=String(s.bundleName||'new_effect.cfxb');state.bundleFiles={...C.blankBundle(),...(s.bundleFiles||{})};state.selectedSampler=String(s.selectedSampler||'');state.selectedRenderer=String(s.selectedRenderer||'');state.codeFile=String(s.codeFile||C.bundleFileList(state.bundleFiles)[0]||'effect.cfx');state.dirtyBundle=!!s.dirtyBundle;parseBundle();refreshProject();renderBundleAll();setView(s.view||'designer')}
  function init(){const type=$('#effectsStuffType');if(type)type.innerHTML=C.EFFECT_TYPES.map(x=>`<option>${safeHtml(x)}</option>`).join('');state.selectedStuff=C.epfStuffsForLayer(state.epf,state.selectedLayer)[0]?.section||'';bind();installMotionResizeObserver();refreshProject();loadBundle({name:'new_effect.cfxb',files:C.blankBundle()});refreshToolStatus();setView('designer')}
  window.WC3_EFFECTS_LAB=Object.freeze({prepare(){refreshToolStatus();refreshProject();renderBundleAll();scheduleEffectsLayoutRefresh('workspace-open',4);},getState:()=>state,getProjectText:()=>C.serializeIni(state.epf.doc),loadProjectText:text=>{state.epf=C.parseEpf(text);state.selectedLayer=state.epf.layers[0]?.section||'';state.selectedStuff=C.epfStuffsForLayer(state.epf,state.selectedLayer)[0]?.section||'';refreshProject();},loadBundleFiles:files=>loadBundle({name:'autotest.cfxb',files}),setBridge:b=>{state.bridge=b;},setTestMode:v=>{state.testMode=!!v;},setMotionDprOverride:v=>{state.motionDprOverride=(v==null||v==='')?null:(Number.isFinite(Number(v))?Number(v):null);scheduleEffectsLayoutRefresh('dpr-override',3);},setView,getView:currentView,applyCodeToState,renderMotion,scheduleLayoutRefresh:scheduleEffectsLayoutRefresh,refreshToolStatus,snapshotState,restoreState});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
